# Generated by Django 3.0.4 on 2020-04-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=300)),
                ('productPrice', models.CharField(max_length=20)),
                ('productDescription', models.TextField()),
                ('productImg1', models.CharField(max_length=300)),
                ('productImg2', models.CharField(max_length=300)),
                ('productImg3', models.CharField(max_length=300)),
            ],
        ),
    ]
